name: Deploy Portfolio to S3

on:
  push:
    branches: [ main ]  # Change 'main' to your desired branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Updated to v3 for Node.js 20 compatibility


      - name: Configure AWS Credentials (replace with your access key and secret key)
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      

      - name: Upload Portfolio to S3 Bucket
        run:
          aws s3 sync . s3://portfolio786 --delete






