name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js
      uses: onramper/action-deploy-aws-static-site@v3.2.0
      with:
        node-version: '20'

    - name: Checkout code
      uses: onramper/action-deploy-aws-static-site@v3.2.0

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Deploy to S3
      run: |
        aws s3 sync . s3://portfolio786 --delete --exclude ".git/*"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: your_aws_region






